baseurl = "localhost/"
languageCode = "en-uk"
metadataformat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = "UA-80660232-2"
canonifyurls = false

title = "MIP specifications"
theme = "docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true

[params]
editURL = "https://github.com/HBPMedical/specifications/edit/master/content/"
themeVariant = "gold" # choose theme variant "green", "gold" , "gray", "blue" (default)
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
author = "HBP SP8 team"
copyright = "Released under the MIT license"
custom_css = []
custom_js = []
description = "Specifications for the Medical Informatics Platform of the Human Brain Project."
favicon = ""
highlight_css = ""
permalink = "#"
provider = ""
repo_url = "https://github.com/HBPMedical/specifications"
version = ""
cde_version = "0.1.6"

[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"

[params.palette]
accent = "teal"
primary = "red"

[social]
github = "HBPMedical"

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-step-backward'></i> Back to HBP Medical Documentation"
identifier = "hbpmeddocs"
url = "https://hbpmedical.github.io/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github repo for this doc"
identifier = "ghspecs"
url = "https://github.com/HBPMedical/specifications"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 20
