baseurl = "https://hbpmedical.github.io/specifications/"
canonifyurls = true
googleAnalytics = "UA-80660232-2"
languageCode = "en-uk"
metadataformat = "yaml"
theme = "hugo-theme-learn"
title = "MIP specifications"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.main]]
name = "Data Capture"
url = "/data-capture"
weight = 10
[[menu.main]]
name = "Data Factory"
url = "/data-factory"
weight = 20
[[menu.main]]
name = "MIP specifications"
url = "/"
weight = 0

[params]
author = "HBP SP8 team"
copyright = "Released under the MIT license"
custom_css = []
custom_js = []
description = "Specifications for the Medical Informatics Platform of the Human Brain Project."
favicon = ""
highlight_css = ""
logo = "images/hbp.png"
permalink = "#"
provider = ""
repo_url = "https://github.com/HBPMedical/specifications"
version = ""
editURL = "https://github.com/HBPMedical/specifications/edit/master/content/"
menu = [ "data-capture", "data-factory", "algorithm-factory", "hospital-database" ]
[params.font]
code = "Ubuntu Mono"
text = "Ubuntu"
[params.palette]
accent = "teal"
primary = "red"
[social]
github = "HBPMedical"
